#define WIFI_SSID_1 "<SSID1>"
#define WIFI_PWD_1 "<PWD1>"
#define WIFI_SSID_2 "<SSID2>"
#define WIFI_PWD_2 "<PWD2>"
#define DISCORD_WEBHOOK_URL "https://discord.com/api/webhooks/XXXXXXXXXXXX/XXXXXXXXX"